-- ===========================================================================
--  自动归属导入：把富来小厨整本菜单导入 demo@alpinedd.com 名下的商家
--  用法：整个文件粘进 Supabase → SQL Editor → Run（无需手动填 slug）
--  它会：① 按邮箱找到该账号的商家 ② 自动启用「菜单设置」③ 导入全部菜品
-- ===========================================================================
do $$
declare v_slug text;
begin
  select t.slug into v_slug
  from public.tenants t
  join auth.users u on u.id = t.owner_id
  where u.email = 'demo@alpinedd.com'
  order by t.created_at
  limit 1;

  if v_slug is null then
    raise exception '找不到 demo@alpinedd.com 名下的商家——请先用该账号登录 bentoos.io 建一个商家';
  end if;
  raise notice '导入到商家: %', v_slug;

  -- 确保该商家启用了「菜单设置」
  update public.tenants
    set enabled = (
      select jsonb_agg(distinct e)
      from jsonb_array_elements(enabled || '["menu-generator"]'::jsonb) e
    )
    where slug = v_slug;

  delete from public.menu_items where tenant_slug = v_slug;
  
  insert into public.menu_items (tenant_slug, name_zh, name_en, price, category, sort) values
  -- ── 招牌精选 ─────────────────────────────────────────────
  (v_slug,'荷香笼仔蒸蟹饭','Steamed Crab with Rice in Lotus Leaf',99.99,'招牌精选',1),
  (v_slug,'潮式大拼盘 (大/中)','Chiu Chow Combo Platter (L/M)',85.99,'招牌精选',2),
  (v_slug,'软壳蟹 (椒盐/避风塘)','Soft Shell Crab (Salt & Pepper / Typhoon Shelter)',27.99,'招牌精选',3),
  (v_slug,'椒盐 / 卤水鸭舌','Salt & Pepper or Marinated Duck Tongue',26.99,'招牌精选',4),
  (v_slug,'卤水牛健','Marinated Beef Shank',23.99,'招牌精选',5),
  (v_slug,'干烧白饭鱼菜甫','Dry Fried Whitebait with Preserved Vegetables',30.99,'招牌精选',6),
  (v_slug,'麻辣仙掌','Spicy Duck Web',26.99,'招牌精选',7),
  (v_slug,'煎封马友','Pan Fried Threadfin Fish',23.99,'招牌精选',8),
  (v_slug,'黄金玉子豆腐煲','Golden Japanese Tofu Hot Pot',24.99,'招牌精选',9),
  (v_slug,'韭菜花菜甫煎蛋','Omelette with Chives & Preserved Vegetables',23.99,'招牌精选',10),
  -- ── 滋补菜式 ─────────────────────────────────────────────
  (v_slug,'佛跳墙','Buddha Jumps Over the Wall',null,'滋补菜式',11),
  (v_slug,'蚝皇大鲍鱼','Abalone in Oyster Sauce',null,'滋补菜式',12),
  (v_slug,'鲍翅','Abalone & Shark''s Fin',null,'滋补菜式',13),
  (v_slug,'红烧乳鸽 (预订)','Braised Pigeon (pre-order)',null,'滋补菜式',14),
  -- ── 火锅 ─────────────────────────────────────────────────
  (v_slug,'大补走地鸡锅','Free Range Chicken Hot Pot',45.99,'火锅',15),
  (v_slug,'药材竹丝鸡锅','Herbal Silkie Chicken Hot Pot',50.99,'火锅',16),
  (v_slug,'游水青斑火锅','Live Green Bass Hot Pot',65.99,'火锅',17),
  (v_slug,'游水立鱼火锅','Live Tilapia Hot Pot',39.99,'火锅',18),
  (v_slug,'秘制棱竹羊腩煲','House Special Lamb Brisket Hot Pot',39.99,'火锅',19),
  -- ── 海鲜 ─────────────────────────────────────────────────
  (v_slug,'生猛龙虾','Live Lobster (Steamed / Ginger & Onion / Black Bean)',null,'海鲜',20),
  (v_slug,'生猛温哥华蟹','Live Vancouver Crab',null,'海鲜',21),
  (v_slug,'生猛象拔蚌','Live Geoduck',null,'海鲜',22),
  (v_slug,'生猛游水温哥华虾','Live Shrimp',null,'海鲜',23),
  (v_slug,'XO王子菇桂花蚌','Geoduck with King Mushroom in XO Sauce',45.99,'海鲜',24),
  (v_slug,'油泡桂花蚌','Sauteed Geoduck',40.99,'海鲜',25),
  (v_slug,'生猛游水青斑','Live Green Bass (each)',null,'海鲜',26),
  (v_slug,'生猛游水金山鲷','Live Tilapia (each)',null,'海鲜',27),
  (v_slug,'豉汁左口鱼','Cod with Black Bean Sauce',23.99,'海鲜',28),
  (v_slug,'五柳石斑球','Sliced Grouper (Boneless) with Sweet & Sour Sauce',23.99,'海鲜',29),
  (v_slug,'粟米斑球','Sliced Grouper (Boneless) with Sweet Corn',23.99,'海鲜',30),
  (v_slug,'油泡石斑球','Sauteed Grouper Fillet with Celery & Snow Peas',23.99,'海鲜',31),
  (v_slug,'油泡三鲜','Sauteed Seafood Trio with Celery & Snow Peas',28.99,'海鲜',32),
  (v_slug,'椒盐三鲜','Deep Fried Seafood Trio in Spicy Salt & Pepper',26.99,'海鲜',33),
  (v_slug,'XO三鲜','Seafood Trio in X.O. Sauce',26.99,'海鲜',34),
  (v_slug,'豉汁虾仁带子西兰花','Scallops & Shrimps with Broccoli in Black Bean Sauce',28.99,'海鲜',35),
  (v_slug,'美极虾仁 / 中虾','Pan Fried Shrimps (with or without Shell)',23.99,'海鲜',36),
  (v_slug,'椒盐虾仁','Deep Fried Shrimp with Spicy Salt & Pepper',23.99,'海鲜',37),
  (v_slug,'左宗虾仁','General Tso''s Shrimps',23.99,'海鲜',38),
  (v_slug,'咕噜虾仁','Sweet & Sour Shrimps',23.99,'海鲜',39),
  (v_slug,'四川虾仁','Szechuan Shrimps',23.99,'海鲜',40),
  (v_slug,'腰果虾仁','Sauteed Shrimps with Cashew Nuts',26.99,'海鲜',41),
  (v_slug,'滑蛋虾仁','Shrimps with Scrambled Eggs',23.99,'海鲜',42),
  (v_slug,'虾龙糊','Shrimps with Lobster Sauce',23.99,'海鲜',43),
  (v_slug,'油泡雪豆虾仁','Stir Fried Shrimps with Snow Peas',23.99,'海鲜',44),
  (v_slug,'蒜蓉虾仁','Shrimps with Garlic Sauce',23.99,'海鲜',45),
  (v_slug,'椒盐中虾','Deep Fried Shrimp with Spicy Salt & Pepper (Shells on)',23.99,'海鲜',46),
  (v_slug,'咖喱虾仁','Curry Shrimps',23.99,'海鲜',47),
  (v_slug,'白灼鲜鱿虾仁','Steamed Calamari and Shrimps',24.99,'海鲜',48),
  (v_slug,'椒盐鲜鱿','Deep Fried Calamari with Spicy Salt & Pepper',20.99,'海鲜',49),
  (v_slug,'豉椒鲜鱿','Calamari with Black Bean Sauce',20.99,'海鲜',50),
  (v_slug,'什菜鲜鱿','Sauteed Calamari with Vegetables',20.99,'海鲜',51),
  (v_slug,'椒盐带子','Deep Fried Scallops with Spicy Salt & Pepper',28.99,'海鲜',52),
  (v_slug,'时菜带子','Stir Fried Scallops with Seasonal Vegetables',28.99,'海鲜',53),
  (v_slug,'酥炸生蚝','Deep Fried Oysters',26.99,'海鲜',54),
  (v_slug,'姜葱生蚝','Sauteed Oysters with Ginger & Onion',26.99,'海鲜',55),
  (v_slug,'豉汁炒蚬','Clams in Black Bean Sauce',22.99,'海鲜',56),
  (v_slug,'豉汁青口','Mussels in Black Bean Sauce',16.99,'海鲜',57),
  -- ── 汤羹 ─────────────────────────────────────────────────
  (v_slug,'红烧蟹肉翅','Shark''s Fin & Crab Meat in Thick Soup',35.99,'汤羹',58),
  (v_slug,'红烧鸡丝翅','Shark''s Fin & Shredded Chicken in Thick Soup',32.99,'汤羹',59),
  (v_slug,'节瓜蚬汤','Melon Clams Soup',17.99,'汤羹',60),
  (v_slug,'蟹肉鱼肚羹','Crab Meat and Fish Maw Soup',9.99,'汤羹',61),
  (v_slug,'海皇豆腐羹','Assorted Seafood with Bean Curd Soup',9.99,'汤羹',62),
  (v_slug,'八宝豆腐羹','Eight Treasures with Bean Curd Soup',9.99,'汤羹',63),
  (v_slug,'蟹肉粟米羹','Crab Meat with Sweet Corn Soup',9.99,'汤羹',64),
  (v_slug,'海鲜酸辣汤','Seafood Hot and Sour Soup',9.99,'汤羹',65),
  (v_slug,'酸辣汤','Hot & Sour Soup',8.99,'汤羹',66),
  (v_slug,'西洋菜肉片汤','Watercress with Sliced Pork Soup',8.99,'汤羹',67),
  (v_slug,'西湖牛肉羹','Minced Beef Egg Drop Soup',8.99,'汤羹',68),
  (v_slug,'鸡茸粟米羹','Chicken Sweet Corn Soup',8.99,'汤羹',69),
  (v_slug,'云吞汤','Wonton Soup',8.99,'汤羹',70),
  (v_slug,'鲜菇蛋花汤','Mushroom Egg Drop Soup',8.99,'汤羹',71),
  (v_slug,'鲜虾云吞汤','Shrimp Wonton Soup',9.99,'汤羹',72),
  -- ── 头盘 ─────────────────────────────────────────────────
  (v_slug,'白灼中虾','Boiled Shrimps (Shells on)',16.99,'头盘',73),
  (v_slug,'日式鱿鱼筒','Pan Fried Whole Calamari',13.99,'头盘',74),
  (v_slug,'椒盐豆腐角','Deep Fried Bean Curd with Spicy Salt & Pepper',11.99,'头盘',75),
  (v_slug,'椒盐玉子豆腐','Deep Fried Japanese Tofu with Spicy Salt & Pepper',24.99,'头盘',76),
  (v_slug,'春卷 (每条)','Crispy Vegetable Spring Roll (each)',3.50,'头盘',77),
  (v_slug,'百花酿蟹拑 (每只)','Stuffed Crab Claw (each)',9.99,'头盘',78),
  (v_slug,'炸虾花 (6粒)','Deep Fried Shrimp Balls (6 pcs)',14.99,'头盘',79),
  (v_slug,'炸虾角 (6只)','Deep Fried Shrimp Dumplings (6 pcs)',14.99,'头盘',80),
  (v_slug,'炸鸡翼 (5只)','Deep Fried Chicken Wings (5 pcs)',11.99,'头盘',81),
  (v_slug,'椒盐软壳蟹','Deep Fried Soft Shell Crab with Spicy Salt & Pepper',27.99,'头盘',82),
  (v_slug,'炸大肠','Deep Fried Pork''s Intestine',21.99,'头盘',83),
  (v_slug,'豉汁大豆芽炒大肠','Pork Intestine with Soya Bean Sprouts in Black Bean Sauce',25.99,'头盘',84),
  -- ── 蔬菜豆腐 ─────────────────────────────────────────────
  (v_slug,'清炒雪豆王子菇','Pan Fried Snow Pea with King Mushroom',23.99,'蔬菜豆腐',85),
  (v_slug,'黄金玉子豆腐','King Mushroom with Deep Fried Japanese Bean Curd',23.99,'蔬菜豆腐',86),
  (v_slug,'北菇白菜苗','Baby Bok Choy with Chinese Mushroom',24.99,'蔬菜豆腐',87),
  (v_slug,'四川杂菜','Spicy Stir Fried Mixed Vegetables in Szechuan Sauce',23.99,'蔬菜豆腐',88),
  (v_slug,'炒杂菜','Stir Fried Mixed Fresh Vegetables',19.99,'蔬菜豆腐',89),
  (v_slug,'蒜蓉芥兰','Stir Fried Chinese Broccoli with Minced Garlic',19.99,'蔬菜豆腐',90),
  (v_slug,'罗汉上素','Buddha''s Delight',19.99,'蔬菜豆腐',91),
  (v_slug,'干扁四季豆','Dry Sauteed String Beans Szechuan Style',19.99,'蔬菜豆腐',92),
  (v_slug,'蒜蓉茄子','Eggplant in Garlic Sauce',19.99,'蔬菜豆腐',93),
  (v_slug,'湖南豆腐','Hunan Bean Curd',19.99,'蔬菜豆腐',94),
  (v_slug,'麻婆豆腐','Ma Po Bean Curd',18.99,'蔬菜豆腐',95),
  (v_slug,'红烧豆腐','Braised Bean Curd with Mushroom',18.99,'蔬菜豆腐',96),
  (v_slug,'时菜什锦','Vegetables Chop Suey',18.99,'蔬菜豆腐',97),
  (v_slug,'王子菇扒豆苗','King Mushroom with Snow Pea Leaves',17.99,'蔬菜豆腐',98),
  (v_slug,'蒜蓉豆苗','Snow Pea Leaves with Minced Garlic',26.99,'蔬菜豆腐',99),
  (v_slug,'蒜蓉白菜苗','Baby Bok Choy with Minced Garlic',22.99,'蔬菜豆腐',100),
  -- ── 猪肉牛肉 ─────────────────────────────────────────────
  (v_slug,'鱼香茄子','Eggplant with Ginger and Minced Pork',19.99,'猪肉牛肉',101),
  (v_slug,'豉汁肉碎玉子豆腐','Minced Pork with Japanese Bean Curd in Black Bean Sauce',24.99,'猪肉牛肉',102),
  (v_slug,'蜜汁叉烧','B.B.Q. Pork Slices',19.99,'猪肉牛肉',103),
  (v_slug,'左宗排骨','General Tso''s Ribs',23.99,'猪肉牛肉',104),
  (v_slug,'椒盐肉排','Pork Chop with Spicy Salt & Pepper',19.99,'猪肉牛肉',105),
  (v_slug,'京都肉排','Pork Chop with Special Chef''s Sauce',19.99,'猪肉牛肉',106),
  (v_slug,'咕噜肉','Sweet & Sour Pork with Pineapple',19.99,'猪肉牛肉',107),
  (v_slug,'梅菜扣肉','Pork Belly with Preserved Vegetables',22.99,'猪肉牛肉',108),
  (v_slug,'豉汁蒸排骨','Steamed Pork Spare Ribs in Black Bean Sauce',23.99,'猪肉牛肉',109),
  (v_slug,'蜜汁排骨','Honey Garlic Spare Ribs',23.99,'猪肉牛肉',110),
  (v_slug,'黑椒牛柳丝','Black Pepper Julienne Beef',23.99,'猪肉牛肉',111),
  (v_slug,'蚝皇牛肉','Stir Fried Beef with Oyster Sauce',19.99,'猪肉牛肉',112),
  (v_slug,'紫罗牛肉','Stir Fried Beef with Ginger & Pineapple',19.99,'猪肉牛肉',113),
  (v_slug,'沙爹牛肉','Stir Fried Beef with Satay Sauce',19.99,'猪肉牛肉',114),
  (v_slug,'豉汁四季豆牛肉','Stir Fried Beef with Green Beans in Black Bean Sauce',19.99,'猪肉牛肉',115),
  (v_slug,'姜葱牛肉','Stir Fried Beef with Ginger & Onion',19.99,'猪肉牛肉',116),
  (v_slug,'香橙牛肉','Stir Fried Orange Beef',19.99,'猪肉牛肉',117),
  (v_slug,'油泡雪豆牛肉','Stir Fried Beef with Snow Peas',20.99,'猪肉牛肉',118),
  (v_slug,'豉汁青椒牛肉','Stir Fried Green Pepper Beef in Black Bean Sauce',19.99,'猪肉牛肉',119),
  (v_slug,'湖南牛肉','Hunan Beef',19.99,'猪肉牛肉',120),
  (v_slug,'四川牛肉','Szechuan Beef',19.99,'猪肉牛肉',121),
  (v_slug,'咖喱牛肉','Curry Beef',19.99,'猪肉牛肉',122),
  (v_slug,'腰果牛肉','Stir Fried Beef with Cashew Nuts',22.99,'猪肉牛肉',123),
  (v_slug,'鲜茄牛肉','Stir Fried Beef with Tomato',19.99,'猪肉牛肉',124),
  (v_slug,'西兰花牛肉','Stir Fried Beef with Broccoli',19.99,'猪肉牛肉',125),
  (v_slug,'椒盐牛肉','Deep Fried Beef with Spicy Salt & Pepper',19.99,'猪肉牛肉',126),
  (v_slug,'时菜牛肉','Stir Fried Beef with Chinese Greens',19.99,'猪肉牛肉',127),
  (v_slug,'磨菇牛肉','Stir Fried Beef with Mushroom',19.99,'猪肉牛肉',128),
  (v_slug,'芥兰牛肉','Stir Fried Beef with Chinese Broccoli',19.99,'猪肉牛肉',129),
  (v_slug,'牛肉扒豆苗','Stir Fried Beef with Snow Pea Leaves',19.99,'猪肉牛肉',130),
  (v_slug,'牛肉扒白菜苗','Stir Fried Beef with Baby Bok Choy',25.99,'猪肉牛肉',131),
  (v_slug,'四川脆皮牛肉','Szechuan Crispy Shredded Beef',19.99,'猪肉牛肉',132),
  (v_slug,'凉瓜牛肉','Beef with Bitter Melon',19.99,'猪肉牛肉',133),
  -- ── 鸡鸭 ─────────────────────────────────────────────────
  (v_slug,'脆皮炸子鸡 (全只)','Deep Fried Crispy Chicken (whole)',39.99,'鸡鸭',134),
  (v_slug,'脆皮炸子鸡 (半只)','Deep Fried Crispy Chicken (half)',20.99,'鸡鸭',135),
  (v_slug,'菜胆上汤鸡 (全只)','Steamed Chicken with Seasonal Greens (whole)',39.99,'鸡鸭',136),
  (v_slug,'菜胆上汤鸡 (半只)','Steamed Chicken with Seasonal Greens (half)',22.99,'鸡鸭',137),
  (v_slug,'卤水鸭 (半只)','Marinated Duck (Half)',24.99,'鸡鸭',138),
  (v_slug,'八珍扒鸭','Braised Duck with Assorted Meat and Vegetables',32.99,'鸡鸭',139),
  (v_slug,'生炒走地鸡','Home Special Pan Fried Chicken',23.99,'鸡鸭',140),
  (v_slug,'姜葱霸王鸡','Steamed Chicken with Ginger & Green Onion',22.99,'鸡鸭',141),
  (v_slug,'左宗棠鸡','General Tso''s Chicken',19.99,'鸡鸭',142),
  (v_slug,'咕噜鸡','Sweet & Sour Chicken',19.99,'鸡鸭',143),
  (v_slug,'果仁酥鸡','Soo Guy with Cashew Nuts',19.99,'鸡鸭',144),
  (v_slug,'豉椒鸡片','Stir Fried Chicken Slices with Black Bean Sauce',19.99,'鸡鸭',145),
  (v_slug,'磨菇鸡片','Stir Fried Chicken Slices with Mushroom',19.99,'鸡鸭',146),
  (v_slug,'紫罗鸡片','Stir Fried Chicken Slices with Ginger & Pineapple',19.99,'鸡鸭',147),
  (v_slug,'黑椒鸡片','Black Pepper Sliced Chicken',19.99,'鸡鸭',148),
  (v_slug,'蒜蓉鸡片','Stir Fried Chicken Slices with Garlic Sauce',19.99,'鸡鸭',149),
  (v_slug,'宫保鸡丁','Kung Pao Chicken',19.99,'鸡鸭',150),
  (v_slug,'腰果鸡丁','Stir Fried Diced Chicken with Cashew Nuts',24.99,'鸡鸭',151),
  (v_slug,'咖喱鸡片','Curry Chicken',19.99,'鸡鸭',152),
  (v_slug,'西柠鸡片','Lemon Chicken',19.99,'鸡鸭',153),
  (v_slug,'炸鸡波','Deep Fried Chicken Balls (Sweet & Sour Sauce on side)',19.99,'鸡鸭',154),
  (v_slug,'湖南鸡片','Hunan Chicken',19.99,'鸡鸭',155),
  (v_slug,'四川鸡片','Szechuan Chicken',19.99,'鸡鸭',156),
  (v_slug,'炸鸡翼 (10只)','Deep Fried Chicken Wings (10 pcs)',19.99,'鸡鸭',157),
  (v_slug,'四川辣子鸡','Dry Spicy Chili Chicken',19.99,'鸡鸭',158),
  -- ── 铁板煲仔 ─────────────────────────────────────────────
  (v_slug,'海鲜豆腐煲','Hot Pot with Assorted Seafood & Bean Curd',22.99,'铁板煲仔',159),
  (v_slug,'鸡牛叉烧豆腐煲','Hot Pot with Assorted Meat & Bean Curd',22.99,'铁板煲仔',160),
  (v_slug,'八珍豆腐煲','Bean Curd with Assorted Meat & Seafood',21.99,'铁板煲仔',161),
  (v_slug,'辣子茄虾仁煲','Hot Pot with Spicy Garlic Eggplant & Shrimps',22.99,'铁板煲仔',162),
  (v_slug,'牛腩煲','Hot Pot with Braised Beef Brisket',22.99,'铁板煲仔',163),
  (v_slug,'斑球豆腐煲','Hot Pot with Boneless Grouper',23.99,'铁板煲仔',164),
  (v_slug,'啫啫鸡煲','Hot Pot with Braised Chicken',23.99,'铁板煲仔',165),
  (v_slug,'铁板豉汁斑球','Boneless Grouper with Black Bean on Sizzling Platter',24.99,'铁板煲仔',166),
  (v_slug,'铁板海鲜','Mixed Seafood on Sizzling Platter',26.99,'铁板煲仔',167),
  (v_slug,'铁板XO海鲜','Mixed Seafood in X.O. Sauce on Sizzling Platter',28.99,'铁板煲仔',168),
  (v_slug,'姜葱生蚝煲','Oyster with Ginger & Onion Hot Pot',27.99,'铁板煲仔',169),
  (v_slug,'铁板豉汁牛肉 / 鸡片','Beef / Chicken in Black Bean Sauce on Sizzling Platter',22.99,'铁板煲仔',170),
  (v_slug,'铁板沙爹牛肉 / 鸡片','Beef / Chicken in Satay Sauce on Sizzling Platter',22.99,'铁板煲仔',171),
  (v_slug,'铁板四川鸡片','Szechuan Chicken on Sizzling Platter',22.99,'铁板煲仔',172),
  (v_slug,'铁板中式牛柳','Beef Tenderloin in Chef''s Sauce on Sizzling Platter',23.99,'铁板煲仔',173),
  (v_slug,'铁板黑椒牛柳','Beef Tenderloin with Black Pepper on Sizzling Platter',23.99,'铁板煲仔',174),
  (v_slug,'铁板蜜椒牛仔骨','Sliced Beef Short Ribs with Honey Black Pepper on Sizzling Platter',22.99,'铁板煲仔',175),
  -- ── 芙蓉蛋 ───────────────────────────────────────────────
  (v_slug,'煎蚝饼','Fried Oyster Pancake',23.99,'芙蓉蛋',176),
  (v_slug,'海鲜芙蓉蛋','Mixed Seafood Egg Foo Young',22.99,'芙蓉蛋',177),
  (v_slug,'虾仁芙蓉蛋','Shrimp Egg Foo Young',21.99,'芙蓉蛋',178),
  (v_slug,'牛肉芙蓉蛋','Beef Egg Foo Young',19.99,'芙蓉蛋',179),
  (v_slug,'鸡肉芙蓉蛋','Chicken Egg Foo Young',19.99,'芙蓉蛋',180),
  (v_slug,'杂菜芙蓉蛋','Vegetable Egg Foo Young',18.99,'芙蓉蛋',181),
  (v_slug,'叉烧芙蓉蛋','B.B.Q. Pork Egg Foo Young',19.99,'芙蓉蛋',182),
  (v_slug,'带子芙蓉蛋','Scallops Egg Foo Young',26.99,'芙蓉蛋',183),
  (v_slug,'肉碎蒸水蛋','Steam Egg Custard with Minced Meat',17.99,'芙蓉蛋',184),
  (v_slug,'三式蒸水蛋','Steam Egg Custard with Three Types of Eggs',25.99,'芙蓉蛋',185),
  (v_slug,'鲜茄炒蛋','Scrambled Egg with Tomatoes',17.99,'芙蓉蛋',186),
  -- ── 炒粉面 ───────────────────────────────────────────────
  (v_slug,'北菇干烧伊面','Braised E-Fu Noodles with Chinese Mushroom',18.99,'炒粉面',187),
  (v_slug,'日式炒乌冬','Fried Japanese Udon',19.99,'炒粉面',188),
  (v_slug,'虾仁炒面 / 捞面','Shrimps Chow Mein or Lo Mein',20.99,'炒粉面',189),
  (v_slug,'海鲜炒面 / 捞面','Seafood Chow Mein or Lo Mein',21.99,'炒粉面',190),
  (v_slug,'广东炒面 / 捞面','Cantonese Chow Mein or Lo Mein',20.99,'炒粉面',191),
  (v_slug,'牛肉炒面 / 捞面','Beef with Vegetables Chow Mein or Lo Mein',18.99,'炒粉面',192),
  (v_slug,'鸡肉炒面 / 捞面','Chicken with Vegetables Chow Mein or Lo Mein',18.99,'炒粉面',193),
  (v_slug,'杂菜炒面 / 捞面','Vegetables Chow Mein or Lo Mein',18.99,'炒粉面',194),
  (v_slug,'肉丝炒面 / 捞面','Julienne of Pork Chow Mein or Lo Mein',18.99,'炒粉面',195),
  (v_slug,'三丝炒面捞面','Julienne of Chicken and Pork with Mushroom Chow Mein or Lo Mein',18.99,'炒粉面',196),
  (v_slug,'芽菜干炒面','Bean Sprouts and Soya Sauce Chow Mein',18.99,'炒粉面',197),
  (v_slug,'干炒牛河','Beef and Soya Sauce Fried Rice Noodles',18.99,'炒粉面',198),
  (v_slug,'时菜牛肉炒河','Beef with Vegetables Fried Rice Noodles',18.99,'炒粉面',199),
  (v_slug,'豉椒牛肉炒河','Beef in Black Bean Sauce Fried Rice Noodles',18.99,'炒粉面',200),
  (v_slug,'沙爹牛肉炒河','Satay Beef Fried Rice Noodles',18.99,'炒粉面',201),
  (v_slug,'炒贵刁','Singapore Style Fried Rice Noodles',19.99,'炒粉面',202),
  (v_slug,'星洲炒米','Singapore Style Vermicelli',19.99,'炒粉面',203),
  (v_slug,'马来新竹米','Malaysian Vermicelli',19.99,'炒粉面',204),
  (v_slug,'干炒鸡河','Chicken and Soya Sauce Fried Rice Noodles',18.99,'炒粉面',205),
  (v_slug,'鱼香茄子炒河','Fried Rice Noodle with Eggplant & Garlic Meat Sauce',20.99,'炒粉面',206),
  (v_slug,'麻婆豆腐焖伊面','Braised E-Fu Noodle with Bean Curd & Spicy Meat Sauce',20.99,'炒粉面',207),
  (v_slug,'滑蛋虾仁带子炒河','Fried Rice Noodle with Egg Swirl, Shrimp & Scallop',23.99,'炒粉面',208),
  (v_slug,'黑椒牛柳粒焖伊面','Braised E-Fu Noodle with Diced Beef Tenderloin in Black Pepper',22.99,'炒粉面',209),
  (v_slug,'上海粗炒','Fried Thick Shanghai Noodle',19.99,'炒粉面',210),
  -- ── 煲仔饭 ───────────────────────────────────────────────
  (v_slug,'海鲜煲仔饭','Seafood with Rice in Hot Pot',22.99,'煲仔饭',211),
  (v_slug,'咸鱼肉片煲仔饭','Salted Fish & Sliced Pork with Rice in Hot Pot',22.99,'煲仔饭',212),
  (v_slug,'腊味煲仔饭','Preserved Meat with Rice in Hot Pot',19.99,'煲仔饭',213),
  (v_slug,'排骨煲仔饭','Spare Ribs with Rice in Hot Pot',21.99,'煲仔饭',214),
  (v_slug,'牛肉煲仔饭','Beef with Rice in Hot Pot',21.99,'煲仔饭',215),
  (v_slug,'北菇鸡片煲仔饭','Chinese Mushroom & Fillet Chicken with Rice in Hot Pot',21.99,'煲仔饭',216),
  -- ── 饭类 ─────────────────────────────────────────────────
  (v_slug,'虾龙糊饭','Shrimps in Lobster Sauce on Rice',13.99,'饭类',217),
  (v_slug,'滑蛋虾仁饭','Shrimps with Scrambled Egg Sauce on Rice',13.99,'饭类',218),
  (v_slug,'辣子茄瓜虾仁饭','Shrimps and Eggplants in Chili Sauce on Rice',13.99,'饭类',219),
  (v_slug,'时菜杂烩饭','Assorted Meats and Seafood with Vegetables on Rice',13.99,'饭类',220),
  (v_slug,'咖喱鲜鱿饭','Curry Calamari on Rice',13.99,'饭类',221),
  (v_slug,'豉椒鲜鱿饭','Calamari in Black Bean Sauce on Rice',13.99,'饭类',222),
  (v_slug,'斑腩豆腐饭','Grouper & Bean Curd on Rice',13.99,'饭类',223),
  (v_slug,'粟米斑腩饭','Grouper with Sweet Corn on Rice',13.99,'饭类',224),
  (v_slug,'湖南豆腐饭','Hunan Bean Curd on Rice',12.99,'饭类',225),
  (v_slug,'干扁四季豆饭','Szechuan Dry Fried String Beans on Rice',12.99,'饭类',226),
  (v_slug,'蒜蓉西兰花饭','Broccoli with Garlic on Rice',13.99,'饭类',227),
  (v_slug,'四川脆牛饭','Szechuan Crispy Shredded Beef on Rice',12.99,'饭类',228),
  (v_slug,'四川杂菜饭','Szechuan Mixed Vegetables on Rice',12.99,'饭类',229),
  (v_slug,'什菜豆腐饭','Mixed Vegetables with Bean Curd on Rice',12.99,'饭类',230),
  (v_slug,'辣子茄瓜饭','Spicy Eggplant on Rice',12.99,'饭类',231),
  (v_slug,'麻婆豆腐饭','Ma Po Bean Curd on Rice',12.99,'饭类',232),
  (v_slug,'左宗棠鸡饭','General Tso''s Chicken on Rice',12.99,'饭类',233),
  (v_slug,'咕噜鸡饭','Sweet and Sour Chicken on Rice',12.99,'饭类',234),
  (v_slug,'豉椒鸡片饭','Spicy Chicken in Black Bean Sauce on Rice',12.99,'饭类',235),
  (v_slug,'四季豆鸡片饭','Chicken and String Beans on Rice',12.99,'饭类',236),
  (v_slug,'宫保鸡丁饭','Kung Pao Chicken on Rice',12.99,'饭类',237),
  (v_slug,'咖喱鸡片饭','Chicken with Curry Sauce on Rice',12.99,'饭类',238),
  (v_slug,'粟米鸡粒饭','Chicken with Sweet Corn on Rice',12.99,'饭类',239),
  (v_slug,'湖南鸡片饭','Hunan Chicken on Rice',12.99,'饭类',240),
  (v_slug,'什菜鸡片饭','Chicken with Mixed Vegetables on Rice',12.99,'饭类',241),
  (v_slug,'沙爹鸡片饭','Chicken in Satay Sauce on Rice',12.99,'饭类',242),
  (v_slug,'西柠鸡饭','Lemon Chicken on Rice',13.99,'饭类',243),
  (v_slug,'时菜牛肉饭','Beef with Chinese Green on Rice',12.99,'饭类',244),
  (v_slug,'咖喱牛腩饭','Curry Beef Brisket on Rice',13.99,'饭类',245),
  (v_slug,'鲜茄牛饭','Tomato and Beef on Rice',12.99,'饭类',246),
  (v_slug,'沙爹牛肉饭','Satay Beef on Rice',12.99,'饭类',247),
  (v_slug,'姜葱牛肉饭','Beef with Ginger and Onion on Rice',12.99,'饭类',248),
  (v_slug,'蚝王牛肉饭','Beef in Oyster Sauce on Rice',12.99,'饭类',249),
  (v_slug,'西兰花牛肉饭','Beef and Broccoli on Rice',12.99,'饭类',250),
  (v_slug,'什菜牛肉饭','Beef with Mixed Vegetables on Rice',12.99,'饭类',251),
  (v_slug,'豉椒牛肉饭','Spicy Beef & Green Pepper in Black Bean Sauce on Rice',12.99,'饭类',252),
  (v_slug,'凉瓜牛肉饭','Beef & Bitter Melon on Rice',12.99,'饭类',253),
  (v_slug,'黑椒牛柳饭','Beef Tenderloin in Black Pepper Sauce on Rice',13.99,'饭类',254),
  (v_slug,'四季豆牛肉饭','Beef and String Beans on Rice',12.99,'饭类',255),
  (v_slug,'滑蛋牛肉饭','Beef with Scrambled Egg Sauce on Rice',12.99,'饭类',256),
  (v_slug,'磨菇牛肉饭','Beef and Mushroom on Rice',12.99,'饭类',257),
  (v_slug,'咕噜肉饭','Sweet and Sour Pork on Rice',12.99,'饭类',258),
  (v_slug,'西芹肉丝饭','Julienne of Pork and Celery on Rice',12.99,'饭类',259),
  (v_slug,'时菜叉烧饭','B.B.Q. Pork and Vegetables on Rice',12.99,'饭类',260),
  (v_slug,'椒盐肉排饭','Spicy Pork Chop on Rice',12.99,'饭类',261),
  (v_slug,'卤水鸭饭','Marinated Duck on Rice',14.99,'饭类',262),
  (v_slug,'猪扒煎蛋饭','Pork Chop with Fried Egg on Rice',15.99,'饭类',263),
  (v_slug,'中式牛柳饭','Beef Tenderloin Chinese Style on Rice',13.99,'饭类',264),
  (v_slug,'时菜海鲜饭','Seafood with Vegetables on Rice',13.99,'饭类',265),
  -- ── 炒饭 ─────────────────────────────────────────────────
  (v_slug,'咸鱼鸡粒炒饭','Salted Fish and Diced Chicken Fried Rice',20.99,'炒饭',266),
  (v_slug,'阔佬炒饭','Supreme Fried Rice',21.99,'炒饭',267),
  (v_slug,'福建炒饭','Fried Rice Fu-Kien Style',21.99,'炒饭',268),
  (v_slug,'鸡粒炒饭','Fried Rice with Diced Chicken',17.99,'炒饭',269),
  (v_slug,'生炒牛饭','Fried Rice with Beef',17.99,'炒饭',270),
  (v_slug,'虾仁炒饭','Fried Rice with Shrimp',19.99,'炒饭',271),
  (v_slug,'杂菜炒饭','Fried Rice with Mixed Vegetables',17.99,'炒饭',272),
  (v_slug,'鸳鸯炒饭','Chicken and Shrimp with Creamy Tomato Sauce on Rice',23.99,'炒饭',273),
  (v_slug,'叉烧炒饭','Fried Rice with B.B.Q. Pork',17.99,'炒饭',274),
  (v_slug,'扬州炒饭','Yeung Chow Fried Rice',19.99,'炒饭',275),
  (v_slug,'瑶柱蛋白炒饭','Dried Scallop and Egg White Fried Rice',20.99,'炒饭',276),
  (v_slug,'瑶柱海王炒饭','Dried Scallop and Seafood Fried Rice',23.99,'炒饭',277),
  (v_slug,'鸡牛虾仁炒饭','Chicken, Beef and Shrimp Fried Rice',20.99,'炒饭',278),
  (v_slug,'蛋炒饭','Eggs Fried Rice',15.99,'炒饭',279),
  (v_slug,'白饭','Steamed Rice',3.00,'炒饭',280),
  -- ── 汤粉面 ───────────────────────────────────────────────
  (v_slug,'海鲜汤面','Seafood Noodle Soup',12.99,'汤粉面',281),
  (v_slug,'鱼丸汤面','Fish Ball Noodle Soup',11.99,'汤粉面',282),
  (v_slug,'鱼片汤面','Sliced Fish Noodle Soup',11.99,'汤粉面',283),
  (v_slug,'云吞汤面','Wonton Noodle Soup',11.99,'汤粉面',284),
  (v_slug,'牛丸汤面','Beef Ball Noodle Soup',11.99,'汤粉面',285),
  (v_slug,'双丸汤面','Fish Ball & Beef Ball Noodle Soup',11.99,'汤粉面',286),
  (v_slug,'牛腩云吞汤面','Beef Stew and Wonton Noodle Soup',15.99,'汤粉面',287),
  (v_slug,'卤水鸭汤面','Marinated Duck Noodle Soup',14.99,'汤粉面',288),
  (v_slug,'雪菜肉丝汤米','Vermicelli Soup with Julienne of Pork and Pickles',11.99,'汤粉面',289),
  (v_slug,'叉烧汤面','B.B.Q. Pork Noodle Soup',11.99,'汤粉面',290),
  (v_slug,'牛肉汤面','Beef Noodle Soup',11.99,'汤粉面',291),
  (v_slug,'沙爹鸡 / 牛汤面','Satay Chicken or Satay Beef Noodle Soup',11.99,'汤粉面',292),
  (v_slug,'扬州窝面','Yong Chow Noodle Soup',18.99,'汤粉面',293),
  (v_slug,'虾云吞汤面','Shrimp Wonton Noodle Soup',12.99,'汤粉面',294),
  -- ── 粥类 ─────────────────────────────────────────────────
  (v_slug,'招牌粥','Special Congee',12.99,'粥类',295),
  (v_slug,'鸡片粥','Sliced Chicken Congee',11.99,'粥类',296),
  (v_slug,'牛肉粥','Beef Congee',11.99,'粥类',297),
  (v_slug,'海鲜粥','Seafood Congee',12.99,'粥类',298),
  (v_slug,'鱼片粥','Sliced Fish Congee',11.99,'粥类',299),
  (v_slug,'咸蛋粥','Salted Egg with Congee',11.99,'粥类',300),
  (v_slug,'皮蛋瘦肉粥','Preserved Egg & Minced Pork Congee',11.99,'粥类',301),
  (v_slug,'瑶柱白粥','Plain Congee',11.99,'粥类',302),
  (v_slug,'双蛋芥菜粥','Preserved Eggs and Mustard Green Congee',12.99,'粥类',303),
  (v_slug,'走地鸡粥','Free Range Chicken Congee',12.99,'粥类',304),
  -- ── 酒水饮品 ─────────────────────────────────────────────
  (v_slug,'青岛 / 喜力 / Corona 啤酒','Tsing Tao / Heineken / Corona',7.00,'酒水饮品',305),
  (v_slug,'Sapporo 啤酒','Sapporo',13.00,'酒水饮品',306),
  (v_slug,'本地啤酒','Domestic Beer (Budweiser / Molson / Coors / Labatt)',5.00,'酒水饮品',307),
  (v_slug,'Bar Shots (1-1/4 oz)','Gin / Rum / Vodka / Scotch',8.00,'酒水饮品',308),
  (v_slug,'轩尼诗 V.S.O.P (1 oz)','Hennessy V.S.O.P',12.00,'酒水饮品',309),
  (v_slug,'House Wine (杯 5oz)','House Wine - Glass',7.00,'酒水饮品',310),
  (v_slug,'House Wine (半升)','House Wine - Half Litre',30.00,'酒水饮品',311),
  (v_slug,'House Wine (750ml)','House Wine - Bottle 750ml',45.00,'酒水饮品',312),
  (v_slug,'日本清酒 (小)','Sake - Small (9.03 oz)',15.00,'酒水饮品',313),
  (v_slug,'日本清酒 (瓶)','Sake - Bottle',35.00,'酒水饮品',314),
  (v_slug,'冻柠檬茶 (罐)','Nestea (can 341ml)',3.50,'酒水饮品',315),
  (v_slug,'汽水 (罐)','Pop (can 355ml)',3.00,'酒水饮品',316),
  (v_slug,'汽水 / 苹果橙汁 (瓶)','Pop / Apple / Orange Juice (bottle)',4.00,'酒水饮品',317),
  (v_slug,'王老吉 (罐)','Chinese Herbal Tea (can)',4.00,'酒水饮品',318),
  (v_slug,'豆浆 (杯)','Soya Milk (glass)',4.00,'酒水饮品',319),
  (v_slug,'绿茶 (罐)','Green Tea (can)',4.00,'酒水饮品',320),
  (v_slug,'椰奶 (罐)','Coconut Milk (can)',4.50,'酒水饮品',321),
  (v_slug,'红牛 (罐)','Red Bull (can)',4.00,'酒水饮品',322),
  (v_slug,'茶包 (茉莉花 / 铁观音)','Tea Bag (Jasmine / Tieguanyin)',4.00,'酒水饮品',323);

end $$;
